# Generated by Django 4.2.25 on 2025-11-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=1000)),
                ('country', models.CharField(default='', max_length=1000)),
                ('long', models.FloatField(default=0.0)),
                ('lati', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('email', models.EmailField(default='', max_length=500, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=100)),
                ('plati', models.ManyToManyField(related_name='person_latitude', to='app.data')),
                ('plong', models.ManyToManyField(related_name='person_longitude', to='app.data')),
            ],
        ),
    ]
